//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseTmpSizes
    {
        public int id { get; set; }
        public double base_number { get; set; }
        public double code_surface { get; set; }
        public double orientation { get; set; }
        public double size_number { get; set; }
        public double size_description_id { get; set; }
        public string description { get; set; }
        public double max_value { get; set; }
        public double min_value { get; set; }
    }
}
