//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bases
    {
        public int device_id { get; set; }
        public int number_base_surface { get; set; }
        public double code_surface { get; set; }
        public double orientation { get; set; }
        public double com_1_max { get; set; }
        public double com_1_min { get; set; }
        public double com_2_max { get; set; }
        public double com_2_min { get; set; }
        public double com_3_max { get; set; }
        public double com_3_min { get; set; }
    }
}
