//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseTmpLocations
    {
        public int id { get; set; }
        public double base_number { get; set; }
        public double location_number { get; set; }
        public double size_X_min { get; set; }
        public double size_X_max { get; set; }
        public double size_Y_min { get; set; }
        public double size_Y_max { get; set; }
        public double size_Z_min { get; set; }
        public double size_Z_max { get; set; }
        public string description { get; set; }
    }
}
