//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseForSMS1
    {
        public int id { get; set; }
        public int process_surface_id { get; set; }
        public double number_base_schema { get; set; }
        public int base_id { get; set; }
        public double number_base { get; set; }
        public int base_surface_id { get; set; }
        public double number_variant { get; set; }
        public double number_step { get; set; }
        public bool reverse { get; set; }
        public double number_base_surface { get; set; }
    }
}
