//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class CopySMS1
    {
        public int id { get; set; }
        public int detail_id { get; set; }
        public int surface_id { get; set; }
        public double number_variant { get; set; }
        public double number_step { get; set; }
        public string code_surface { get; set; }
        public string finish { get; set; }
        public double tolerance { get; set; }
        public bool symmetry { get; set; }
        public double zero_point_x { get; set; }
        public double zero_point_y { get; set; }
        public double zero_point_z { get; set; }
        public double surface_size_1 { get; set; }
        public double surface_size_2 { get; set; }
        public double surface_size_3 { get; set; }
        public double surface_size_4 { get; set; }
        public double surface_size_5 { get; set; }
        public double surface_size_6 { get; set; }
        public double surface_size_7 { get; set; }
        public double surface_size_8 { get; set; }
        public double ra { get; set; }
        public double rmax { get; set; }
        public double s { get; set; }
        public double tp { get; set; }
        public double hrc { get; set; }
        public double depth { get; set; }
        public double base_code { get; set; }
        public double orientation { get; set; }
        public int device_id { get; set; }
        public double view_process { get; set; }
        public double number_machining_step { get; set; }
        public bool not_base { get; set; }
        public double number_surface { get; set; }
    }
}
