//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSizeSurfaces
    {
        public int size_id { get; set; }
        public int surface_id { get; set; }
        public int size_description_id { get; set; }
        public double nominal { get; set; }
        public string finish { get; set; }
        public double max_deviation { get; set; }
        public double min_deviation { get; set; }
        public double tolerance { get; set; }
        public bool symmetry { get; set; }
    
        public virtual DSurfaces DSurfaces { get; set; }
    }
}
