//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSurfaces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSurfaces()
        {
            this.DGeometries = new HashSet<DGeometries>();
            this.DLocations = new HashSet<DLocations>();
            this.DRelationSizes = new HashSet<DRelationSizes>();
            this.DSizeSurfaces = new HashSet<DSizeSurfaces>();
        }
    
        public int surface_id { get; set; }
        public int detail_id { get; set; }
        public double number_surface { get; set; }
        public string code_surface { get; set; }
        public double zero_point_X { get; set; }
        public double zero_point_Y { get; set; }
        public double zero_point_Z { get; set; }
        public double ra { get; set; }
        public double rmax { get; set; }
        public double s { get; set; }
        public double tp { get; set; }
        public double hrc { get; set; }
        public double depth { get; set; }
        public double internal_stress_1 { get; set; }
        public double internal_stress_2 { get; set; }
        public double internal_stress_3 { get; set; }
        public bool constructor_base { get; set; }
        public double orientation { get; set; }
        public bool requirement { get; set; }
        public string image { get; set; }
    
        public virtual DDescriptions DDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGeometries> DGeometries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DLocations> DLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRelationSizes> DRelationSizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSizeSurfaces> DSizeSurfaces { get; set; }
    }
}
