//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBaseLocations
    {
        public int base_requirement_id { get; set; }
        public double location_number { get; set; }
        public double size_x_min { get; set; }
        public double size_x_max { get; set; }
        public double size_y_min { get; set; }
        public double size_y_max { get; set; }
        public double size_z_min { get; set; }
        public double size_z_max { get; set; }
    
        public virtual EBaseSurfaces EBaseSurfaces { get; set; }
    }
}
