//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBaseSurfaces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBaseSurfaces()
        {
            this.EBaseLocations = new HashSet<EBaseLocations>();
            this.EBaseSizes = new HashSet<EBaseSizes>();
        }
    
        public int base_requirement_id { get; set; }
        public int base_scheme_id { get; set; }
        public double base_number { get; set; }
        public string code_surface { get; set; }
        public double orientation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBaseLocations> EBaseLocations { get; set; }
        public virtual EBaseSchemes EBaseSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBaseSizes> EBaseSizes { get; set; }
    }
}
