//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECarriages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ECarriages()
        {
            this.EFeeds = new HashSet<EFeeds>();
            this.ERelationCarriages = new HashSet<ERelationCarriages>();
        }
    
        public int carriage_id { get; set; }
        public int lathe_id { get; set; }
        public string name { get; set; }
        public double position_count { get; set; }
        public bool synchronization { get; set; }
        public bool parallel_processing { get; set; }
        public double move_x_value { get; set; }
        public double move_y_value { get; set; }
    
        public virtual ELathes ELathes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFeeds> EFeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERelationCarriages> ERelationCarriages { get; set; }
    }
}
