//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDevices
    {
        public int device_id { get; set; }
        public int base_scheme_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public bool enabled { get; set; }
        public string description { get; set; }
    
        public virtual EBaseSchemes EBaseSchemes { get; set; }
    }
}
