//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGeoSTmps
    {
        public int id { get; set; }
        public int deviation_id { get; set; }
        public double code_deviation { get; set; }
        public double value_deviation { get; set; }
        public double class_deviation { get; set; }
    }
}
