//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERelationCarriages
    {
        public int relation_id { get; set; }
        public int carriage_id { get; set; }
        public int relation_carriage_id { get; set; }
    
        public virtual ECarriages ECarriages { get; set; }
    }
}
