//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESpeeds
    {
        public int speed_id { get; set; }
        public int spindle_id { get; set; }
        public bool reverse { get; set; }
        public double value { get; set; }
    
        public virtual ESpindles ESpindles { get; set; }
    }
}
