//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESpindles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESpindles()
        {
            this.ESpeeds = new HashSet<ESpeeds>();
        }
    
        public int spindle_id { get; set; }
        public int lathe_id { get; set; }
        public string name { get; set; }
        public bool step_feed { get; set; }
        public double min_value { get; set; }
        public double max_value { get; set; }
        public bool reverse_feed { get; set; }
    
        public virtual ELathes ELathes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESpeeds> ESpeeds { get; set; }
    }
}
