//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETransitionBases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ETransitionBases()
        {
            this.ETransitionBaseTolerances = new HashSet<ETransitionBaseTolerances>();
        }
    
        public int base_requirement_id { get; set; }
        public int transition_id { get; set; }
        public double base_number { get; set; }
        public string code_surface { get; set; }
    
        public virtual ETransitions ETransitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETransitionBaseTolerances> ETransitionBaseTolerances { get; set; }
    }
}
