//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETransitionBaseTolerances
    {
        public int base_requirement_id { get; set; }
        public double size_number { get; set; }
        public double tolerance { get; set; }
        public int size_description_id { get; set; }
    
        public virtual ETransitionBases ETransitionBases { get; set; }
    }
}
