//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETransitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ETransitions()
        {
            this.ETransitionBases = new HashSet<ETransitionBases>();
            this.ETransitionGeometryInputs = new HashSet<ETransitionGeometryInputs>();
            this.ETransitionGeometryOutputs = new HashSet<ETransitionGeometryOutputs>();
            this.ETransitionSizes = new HashSet<ETransitionSizes>();
        }
    
        public int transition_id { get; set; }
        public int base_scheme_id { get; set; }
        public int type_process_id { get; set; }
        public string code_output_surface { get; set; }
        public double output_tolerance { get; set; }
        public double output_ra { get; set; }
        public double output_rmax { get; set; }
        public double output_tp { get; set; }
        public double output_s { get; set; }
        public double output_hrc { get; set; }
        public double output_depth { get; set; }
        public double output_internalstress_1 { get; set; }
        public double output_internalstress_2 { get; set; }
        public double output_internalstress_3 { get; set; }
        public string code_input_surface { get; set; }
        public double input_tolerance { get; set; }
        public double input_ra { get; set; }
        public double input_rmax { get; set; }
        public double input_tp { get; set; }
        public double input_s { get; set; }
        public double input_hrc { get; set; }
        public double input_depth { get; set; }
        public double input_internalstress_1 { get; set; }
        public double input_internalstress_2 { get; set; }
        public double input_internalstress_3 { get; set; }
        public string mark_material { get; set; }
        public bool enabled { get; set; }
    
        public virtual EBaseSchemes EBaseSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETransitionBases> ETransitionBases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETransitionGeometryInputs> ETransitionGeometryInputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETransitionGeometryOutputs> ETransitionGeometryOutputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETransitionSizes> ETransitionSizes { get; set; }
    }
}
