//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Bonus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETransitionGeometryOutputs
    {
        public int transition_id { get; set; }
        public int code_deviation_id { get; set; }
        public double value { get; set; }
        public double class_ { get; set; }
    
        public virtual ETransitions ETransitions { get; set; }
    }
}
